[package]
name = "projects_a"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = [ "postgres" ] }
uuid = { version = "1.8.0", features = ["v4"] }
chrono = "0.4.38"
