[package]
name = "projects_b"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = [ "postgres" ] }
uuid = { version = "1.8.0", features = ["serde", "v4"] }
tokio = { version = "1.38.0", features = ["full"] }
csv = "1.3.0"
