[package]
name = "projects_b"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = "0.6.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tokio = { version = "1.23.0", features = ["full"] }
csv = "1.1.6"
chrono = "0.4.19"
config = "0.13.3"
async-trait = "0.1.58"
