[package]
name = "trades_a"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "^1.0.117"
serde = { version = "^1.0.203", features = ["derive"] }
csv = "1.3.0"
mysql = "^25.0.1"
secrecy = "0.8.0"
serde_with = "3.8.1"
log = "0.4.21"
log4rs = "1.3.0"
anyhow = "1.0.86"
