[package]
name = "crash_reporter_b"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.27.0"
tokio = { version = "1.38.1", features = ["full"] }
tokio-stream = "0.1.15"
tungstenite = "0.23.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
