[package]
name = "task_times"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }

[lib]
name = "task_times_lib"
crate-type = ["rlib"]
